### ISSUE TITLE
After adding the nefit Easy it is unable to connect

### ISSUE THREAD

**Issue by Rob-Houweling** [athombv/nl.nefit.easy#1]
When I add the thermostat it seems to work fine, but when I want to change the temperature it immediately breaks with the message "het apparaat kon niet worden bereikt". I already sent a log a while back: D35C7C8973
![screenshot_20160517-115450](https://cloud.githubusercontent.com/assets/5127988/15318450/5c75bd8c-1c26-11e6-9724-a8b681fba9f1.png)

**Comment by RobinBol** [comment]
Seemed to be a faulty password. Will look at including a better password check in the next version of the app.
