### ISSUE TITLE
Rounding up/down on 0.5 degrees

### ISSUE THREAD

**Issue by jeroenvano** [athombv/nl.nefit.easy#2]
Just a small practical issue that could be optimized. 

Currently temp reporting is rounded up or down on 0.5 degrees
e.g. measured 21.4 degrees becomes 21.5 in Homey and 21.2 becomes 21.

Nefit Easy gives option to also increase/degrease in 0.1 degrees steps this only works 100% accurate with Homey if also temp reporting would support 0.1 degrees reporting.

Love the app ;)

**Comment by RobinBol** [comment]
Hi! Thanks for the suggestion, that would indeed be a welcome improvement. Will add it to my todo-list.

**Comment by RobinBol** [comment]
Would you be able to test the app before I release it? So upload/run it on your Homey from your command prompt/terminal? Then I can make the changes and you can test whether it works correctly (we don't have an Easy installed at the office).

**Comment by RobinBol** [comment]
If you are not familiar with this, please look here: https://developers.athom.com/library/getting-started/

And download the app from the `temp_rounding` branch which can be found here: https://github.com/athombv/nl.nefit.easy/tree/temp_rounding

**Comment by jeroenvano** [comment]
@RobinBol I will be able to install and run it on my Homey from the command prompt/terminal. Just need to find some time to do the testing, hopefully this weekend. I will give you a shout as soon as I have the first test results. Thanks for taking the time to add this improvement!

**Comment by jeroenvano** [comment]
@RobinBol I am unable to unzip the app as I ger 260 errors due to exceeding Total path and file name length. This can not exceed 260 characters on Windows.

!   C:\Hmy\nl.nefit.easy-temp_rounding.zip: Cannot create folder nl.nefit.easy-temp_rounding\node_modules\nefit-easy-commands\node_modules\nefit-easy-core\node_modules\node-xmpp-client\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi
    De bestandsnaam of -extensie is te lang.

    Total path and file name length must not exceed 260 characters
    Het systeem kan het opgegeven pad niet vinden.

Can you shorten the path and filenames?

**Comment by RobinBol** [comment]
Well, not really:P Could you try this? https://geeznblogged.wordpress.com/2013/01/08/are-you-facing-total-path-and-file-name-length-must-not-exceed-260-characters-error-while-unzipping/

**Comment by jeroenvano** [comment]
Same issue with less errors :(   Sorry for running Windows ...

2016-12-07 16:34 GMT+01:00 Robin Bolscher <notifications@github.com>:

**Comment by RobinBol** [comment]
Wow okay..:p Ehm, you could install de GitHub Desktop client and clone the repo (make sure to use right branch).

**Comment by jeroenvano** [comment]
Installing, I will give it a try later tonight

2016-12-07 17:12 GMT+01:00 Robin Bolscher <notifications@github.com>:

**Comment by RobinBol** [comment]
Great, thanks!

**Comment by jeroenvano** [comment]
You're not going to believe this:

[image: Inline afbeelding 2]

**Comment by RobinBol** [comment]
Believe what?:)

**Comment by jeroenvano** [comment]
Didn't you get the picture attached?  Same error in Git desktop.

2016-12-07 18:26:39.8111|WARN|thread: 1|StandardUserErrors|Showing user
error The clone operation could not be completed because some files exceed
the maximum file path length that Windows defines - for example:
C:\Hmy\nl.nefit.easy\node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/istanbul/node_modules/handlebars/node_modules/uglify-js/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules.
 You may be able to workaround this issue by cloning the repository to a
folder closer to the root of the drive.


2016-12-07 18:19 GMT+01:00 Robin Bolscher <notifications@github.com>:

**Comment by RobinBol** [comment]
I removed the nefit-easy-commands node_module for you. To install clone the branch and cd into nl.nefit.easy and perfom `npm install nefit-easy-commands`. That should work

**Comment by jeroenvano** [comment]
Hi Robin,

Not sure if I installed correctly but the app is running stable after
installation:

C:\Hmy>cd nl.nefit.easy-temp_rounding

C:\Hmy\nl.nefit.easy-temp_rounding>npm install nefit-easy-commands
nefit-easy-commands@1.8.0 node_modules\nefit-easy-commands
├── require-all@2.0.0
├── bluebird@3.4.6
└── nefit-easy-core@2.0.0 (promise-queue@2.2.3, http-string-parser@0.0.5,
debug@2.3.3, node-xmpp-client@3.1.1)

C:\Hmy\nl.nefit.easy-temp_rounding>athom project --install
1/3 - Archiving...
2/3 - Uploading to Homey @ 10.2.11.15:80...
3/3 - Installed `nl.nefit.easy`

C:\Hmy\nl.nefit.easy-temp_rounding>

When adding the Nefit Easy I get the following error:

"Homey kon je Nefit Easy niet vinden, of dit apparaat is al toegevoegd,
controleer of de gegevens hieronder kloppen en probeer opnieuw."

I removed the org appstore installed version before installing locally. So
the device can not be already excising. The serial,access code and password
are correct.

Any clue?

Regards,
Jeroen



2016-12-08 9:50 GMT+01:00 Robin Bolscher <notifications@github.com>:

**Comment by RobinBol** [comment]
Ok, might be that the device is still installed but not shown.

Install the official app from the app store, most likely the device will pop back up. Then remove the device before de-installing the app. Then install the `nl.nefit.easy-temp_rounding` again.

**Comment by jeroenvano** [comment]
Got it - that fixed the issue. Testing now the rounding up/down on 0.1C

2016-12-08 15:25 GMT+01:00 Robin Bolscher <notifications@github.com>:

**Comment by jeroenvano** [comment]
Trigger [IF] card temperature reading value reports correctly on 0.1C
degrees accurate into a variable
Trigger [IF] card *set* temperature reading value reports correctly on 0.1C
degrees accurate into a variable

On the condition [THEN] card to set the new temperature still steps up/down
in 0.5 are available (not sure if this is practical on a slider to also
enable 0.1 steps here)

From a variable perspective this is now 100% accurate to set conditions
"heating-on" and "heating-off" that are used in other flows.

Good work, if you do not want to change the slider, this is ready for
release.

Regards,
Jeroen





2016-12-08 16:01 GMT+01:00 Jeroen van Oosterhout <joosterhout@gmail.com>:

**Comment by RobinBol** [comment]
Great, thanks for testing!

The .5 rounding in mobile/flow cards is something that is handled generically by Homey, I can not change that in this app unfortunately but thanks for letting me know.

App is updated and published in the app store!

**Comment by jeroenvano** [comment]
Ok NP glad to have been of help

2016-12-08 16:31 GMT+01:00 Robin Bolscher <notifications@github.com>:
