### ISSUE TITLE
SDK2 support and additional capabilities

### ISSUE THREAD

**Issue by robertklep** [athombv/nl.nefit.easy#3]
Are there any ongoing efforts to move this app to SDK2? If not, I'd be happy to take a stab at it.

I was also wondering about additional capabilities for the `thermostat` device. For instance, in NL a thermostat is typically used to direct a central heating system, for which `pressure` may be a useful capability. It's something that the Easy can be queried for (at least when combined with a Nefit boiler).

Also, I would like to expose the "boiler indicator" value, which represents the state of the boiler ("hot water", "central heating", "off"). Imagine a flow where you could check if the kids aren't taking too long in the shower, based on the "hot water" indication.

Lastly, the "user mode": if the thermostat is running in manual mode or a clock program.

(bonus capability: gas usage)

I think all these capabilities aren't specific for the Easy so could be used by other thermostat drivers as well.

**Comment by RobinBol** [comment]
We are not planning on rewriting the app to SDKv2 anytime soon, so if you like, take a shot! Most of the things you describe are possible using Homeys current capabilities.

**Comment by RobinBol** [comment]
Published in the beta channel.
